#!/bin/bash
#set -x
while [ $# -gt 1 ] ; do
      echo $1;
      if test "$1" = "-o" ; then
      	  O=$2
	  E=$(echo $O | sed 's,^.*\.,,g')
	  shift
	  shift
       else
	 shift
       fi
done

TFN=$($(dirname $0)/mktmp $1)

$MAKEINFO --latex $1 --output $TFN
latex -output-format=$E $TFN
mv $TFN $O
